//
// Challenge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** info of sigle challenge */
public struct Challenge: Codable {

    public var challengeId: Int
    public var challengeName: String
    public var challengeImage: String
    public var challengeDDay: Int?

    public init(challengeId: Int, challengeName: String, challengeImage: String, challengeDDay: Int? = nil) {
        self.challengeId = challengeId
        self.challengeName = challengeName
        self.challengeImage = challengeImage
        self.challengeDDay = challengeDDay
    }

}
