//
// ChallengeInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 홈 페이지에서 보여주는 용. 챌린지 이름, d-day, 광고, 등등 포함 가능 */
public struct ChallengeInfo: Codable {

    public var result: Bool
    public var challengeName: String?
    public var challengeDDay: String?
    public var habits: [Habit]?

    public init(result: Bool, challengeName: String? = nil, challengeDDay: String? = nil, habits: [Habit]? = nil) {
        self.result = result
        self.challengeName = challengeName
        self.challengeDDay = challengeDDay
        self.habits = habits
    }

}
