//
// HabitDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 세부 습관 페이지에서 보여주는 습관 */
public struct HabitDetail: Codable {

    public var userHabitId: Int?
    public var createDate: String?
    public var time: String?
    public var alarmFlag: Bool?
    public var alarmMusic: String?
    public var alarmHaptic: String?
    public var repeatMon: Bool?
    public var repeatTue: Bool?
    public var repeatWed: Bool?
    public var repeatThu: Bool?
    public var repeatFri: Bool?
    public var repeatSat: Bool?
    public var repeatSun: Bool?
    public var memo: String?
    public var history: [HabitHistory]?

    public init(userHabitId: Int? = nil, createDate: String? = nil, time: String? = nil, alarmFlag: Bool? = nil, alarmMusic: String? = nil, alarmHaptic: String? = nil, repeatMon: Bool? = nil, repeatTue: Bool? = nil, repeatWed: Bool? = nil, repeatThu: Bool? = nil, repeatFri: Bool? = nil, repeatSat: Bool? = nil, repeatSun: Bool? = nil, memo: String? = nil, history: [HabitHistory]? = nil) {
        self.userHabitId = userHabitId
        self.createDate = createDate
        self.time = time
        self.alarmFlag = alarmFlag
        self.alarmMusic = alarmMusic
        self.alarmHaptic = alarmHaptic
        self.repeatMon = repeatMon
        self.repeatTue = repeatTue
        self.repeatWed = repeatWed
        self.repeatThu = repeatThu
        self.repeatFri = repeatFri
        self.repeatSat = repeatSat
        self.repeatSun = repeatSun
        self.memo = memo
        self.history = history
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userHabitId
        case createDate
        case time
        case alarmFlag = "alarm_flag"
        case alarmMusic = "alarm_music"
        case alarmHaptic = "alarm_haptic"
        case repeatMon
        case repeatTue
        case repeatWed
        case repeatThu
        case repeatFri
        case repeatSat
        case repeatSun
        case memo
        case history
    }

}
