//
// HabitHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** a single history of habit */
public struct HabitHistory: Codable {

    public var habitId: Int
    public var date: String?
    public var doneFlag: Bool

    public init(habitId: Int, date: String? = nil, doneFlag: Bool) {
        self.habitId = habitId
        self.date = date
        self.doneFlag = doneFlag
    }

}
