//
// HabitHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** a single history of habit */
public struct HabitHistory: Codable {

    public var id: Int
    public var date: String
    public var doneFlag: Bool

    public init(id: Int, date: String, doneFlag: Bool) {
        self.id = id
        self.date = date
        self.doneFlag = doneFlag
    }

}
