//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A User who is going to participate in challenge */
public struct User: Codable {

    public var id: Int64
    public var username: String
    public var pw: String

    public init(id: Int64, username: String, pw: String) {
        self.id = id
        self.username = username
        self.pw = pw
    }

}
