//
// HabitDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 세부 습관 페이지에서 보여주는 습관 */
public struct HabitDetail: Codable {

    public var userHabitId: Int
    public var createDate: String
    public var alarmFlag: Bool
    /** form; 06:30:00 */
    public var alarmTime: String?
    public var alarmMusic: String?
    public var alarmHaptic: String?
    public var repeatMon: Bool?
    public var repeatTue: Bool?
    public var repeatWed: Bool?
    public var repeatThu: Bool?
    public var repeatFri: Bool?
    public var repeatSat: Bool?
    public var repeatSun: Bool?
    public var memo: String?
    public var habitHistories: [HabitHistory]?

    public init(userHabitId: Int, createDate: String, alarmFlag: Bool, alarmTime: String? = nil, alarmMusic: String? = nil, alarmHaptic: String? = nil, repeatMon: Bool? = nil, repeatTue: Bool? = nil, repeatWed: Bool? = nil, repeatThu: Bool? = nil, repeatFri: Bool? = nil, repeatSat: Bool? = nil, repeatSun: Bool? = nil, memo: String? = nil, habitHistories: [HabitHistory]? = nil) {
        self.userHabitId = userHabitId
        self.createDate = createDate
        self.alarmFlag = alarmFlag
        self.alarmTime = alarmTime
        self.alarmMusic = alarmMusic
        self.alarmHaptic = alarmHaptic
        self.repeatMon = repeatMon
        self.repeatTue = repeatTue
        self.repeatWed = repeatWed
        self.repeatThu = repeatThu
        self.repeatFri = repeatFri
        self.repeatSat = repeatSat
        self.repeatSun = repeatSun
        self.memo = memo
        self.habitHistories = habitHistories
    }

}
