//
// ChallengeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RxSwift

open class ChallengeAPI {
    /**
     모든 챌린지 리스트 가져오기
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Observable<[Challenge]>
     */
    open class func allChallengesGet(apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue) -> Observable<[Challenge]> {
        return Observable.create { observer -> Disposable in
            allChallengesGetWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    observer.onNext(response.body!)
                case let .failure(error):
                    observer.onError(error)
                }
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    /**
     모든 챌린지 리스트 가져오기
     - GET /allChallenges
     - returns: RequestBuilder<[Challenge]> 
     */
    open class func allChallengesGetWithRequestBuilder() -> RequestBuilder<[Challenge]> {
        let path = "/allChallenges"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Challenge]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     {userId}가 속한 챌린지의 습관들 불러오기
     
     - parameter userId: (query) PK of user 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Observable<ChallengeInfo>
     */
    open class func challengeGet(userId: Int64, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue) -> Observable<ChallengeInfo> {
        return Observable.create { observer -> Disposable in
            challengeGetWithRequestBuilder(userId: userId).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    observer.onNext(response.body!)
                case let .failure(error):
                    observer.onError(error)
                }
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    /**
     {userId}가 속한 챌린지의 습관들 불러오기
     - GET /challenge
     - parameter userId: (query) PK of user 
     - returns: RequestBuilder<ChallengeInfo> 
     */
    open class func challengeGetWithRequestBuilder(userId: Int64) -> RequestBuilder<ChallengeInfo> {
        let path = "/challenge"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "user_id": userId.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ChallengeInfo>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
